Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,53 +6,33 @@ on:
       - main  
 
 jobs:
-  build:
+  deploy:
+    name: Deploy Application
     runs-on: ubuntu-latest
 
     env:
-      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       EC2_HOST: ${{ secrets.EC2_HOST }}
       EC2_USER: ${{ secrets.EC2_USER }}
       EC2_KEY: ${{ secrets.EC2_KEY }}
 
     steps:
-      # Step 1: Checkout the repository
-      - name: Checkout Code
-        uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-      # Step 2: Set up Docker
-      - name: Set up Docker
-        uses: docker/setup-buildx-action@v1
-
-      # Step 3: Get the current Git commit hash
-      - name: Get the Git commit hash
-        id: vars
-        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-
-      # Step 4: Install Docker Compose
-      - name: Install Docker Compose
-        run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
-
-      # Step 5: Build and push the Docker images using Docker Compose
-      - name: Build and Push Docker Images
-        run: |
-          docker-compose -f docker-compose.yml build
-          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-          docker-compose -f docker-compose.yml push
-
-      # Step 6: SSH into EC2 and deploy Docker containers using Docker Compose
-      - name: Deploy to EC2
+      - name: Deploy to Production Server via SSH
         uses: appleboy/ssh-action@v0.1.3
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_KEY }}
+          port: 22
           script: |
-            cd /home/ubuntu/workspace/very-chaotic 
-            sudo docker-compose pull
-            sudo docker-compose down
-            sudo docker-compose up -d
-
+            set -e  # Exit if any command fails
+            cd /home/ubuntu/workspace/very-chaotic
+            # Pull the latest changes from GitHub
+            git pull origin main
+            docker-compose down
+            docker-compose build
+            docker-compose up -d
+            # Clean up old, unused Docker images
+            docker image prune -f
